backend:
  # Use Netlify Identity as backend
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets

collections:
  - name: general
    label: General
    create: false
    editor:
      preview: false
    files:
      - name: general
        label: General
        file: src/_data/dataNetlify.json
        description: General info
        fields:
          - name: firstName
            label: First Name
            widget: string
          - name: lastName
            label: last Name
            widget: string
          - name: sections
            label: Sections
            widget: list
            field: { name: title, label: Title, widget: string }
          - name: colors
            label: Colors
            widget: object
            fields:
              - name: primary
                label: Primary
                widget: color 
              - name: profileBorder
                label: Profile Image Border
                widget: color
                enableAlpha: true
      - name: intro
        label: Introduction
        file: src/_includes/intro.md
        description: General info
        fields:
          - name: firstName
            label: First Name
            widget: string
          - name: lastName
            label: last Name
            widget: string
          - name: colors
            label: Colors
            widget: object
            fields:
              - name: primary
                label: Primary
                widget: color 
              - name: profileBorder
                label: Profile Image Border
                widget: color
                enableAlpha: true
  # - name: sections # Used in routes, e.g., /admin/collections/sections
  #   label: Sections # Used in the UI
  #   label_singular: Section
  #   description: The top-level categories, i.e. 'Experience', 'Education', 'References', etc.
  #   folder: src/sections # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{slug}}" # Filename template
  #   fields: # The fields for each document, usually in front matter
  #     - label: Layout
  #       name: layout
  #       widget: select,
  #       options:
  #         [
  #           { label: List, value: layouts/sections/list },
  #           { label: Timeline, value: layouts/sections/timeline },
  #         ]
  - name: "entries"
    label: "Entries"
    label_singular: "Entry"
    description: "Anything that you want to put on your portfolio"
    folder: "src/entries"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Section",
          name: "tags",
          widget: "relation",
          collection: "general",
          value_field: "general.sections.*.title",
          display_fields: ["general.sections.*.title"],
          search_fields: ["general.sections.*.title"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Skills", name: "skills", widget: "list" }
