backend:
  # Use Netlify Identity as backend
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets

publish_mode: editorial_workflow

collections:
  - name: general
    label: General
    create: false
    editor:
      preview: false
    files:
      - name: general
        label: General
        file: src/_data/data.json
        description: Just some basic info
        fields:
          - name: firstName
            label: First Name
            widget: string
          - name: lastName
            label: last Name
            widget: string
          - name: sections
            label: Sections
            label_singular: Section
            widget: list
          - name: colors
            label: Colors
            widget: object
            fields:
              - name: primary
                label: Primary
                widget: color
                allowInput: true
              - name: primaryLight
                label: Primary Light
                widget: color
                allowInput: true
              - name: accent
                label: Accent
                widget: color
                allowInput: true
      - name: intro
        label: Introduction
        file: src/_includes/intro.md
        description: A brief paragraph or two about you
        fields:
          - name: body
            label: Body
            buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
            editor_components: []
            widget: markdown
  - name: entries
    label: Entries
    label_singular: Entry
    description: Anything that you want to put on your portfolio
    folder: src/entries
    create: true
    slug: "{{slug}}"
    fields:
      - label: Section
        name: tags
        widget: relation
        collection: general
        file: general
        value_field: sections.*
        display_fields: [sections.*]
        search_fields: [sections.*]
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string }
      - { label: Skills, name: skills, widget: list }
      - { label: Image, name: image, widget: image }
