backend:
  # Use Netlify Identity as backend
  name: git-gateway
  branch: master
media_folder: "src/assets"
public_folder: "/assets"

collections:
  - name: "sections" # Used in routes, e.g., /admin/collections/blog
    label: "Sections" # Used in the UI
    folder: "src/sections" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "select",
          options: ["list", "timeline"],
        }
      - { label: "Title", name: "title", widget: "string" }
