backend:
  # Use Netlify Identity as backend
  name: git-gateway
  branch: master
media_folder: src/assets/images
public_folder: /assets

collections:
  - name: general
    label: General
    create: false
    editor:
      preview: false
    files:
      - name: general
        label: General
        file: src/_data/data.json
        description: Just some basic info
        fields:
          - name: firstName
            label: First Name
            widget: string
          - name: lastName
            label: last Name
            widget: string
          - name: phone
            label: Phone Number
            widget: string
          - name: email
            label: Email
            widget: string
          - name: sections
            label: Sections
            label_singular: Section
            widget: list
          - name: colors
            label: Colors
            widget: object
            fields:
              - name: primary
                label: Primary
                widget: color
                allowInput: true
                enableAlpha: true
              - name: headerBoxStart
                label: Header Box Gradient - Start
                widget: color
                allowInput: true
                enableAlpha: true
              - name: headerBoxEnd
                label: Header Box Gradient - End
                widget: color
                allowInput: true
                enableAlpha: true
              - name: profileBorder
                label: Profile Border
                widget: color
                allowInput: true
                enableAlpha: true
          - name: socialIcons
            label: Social Icons
            label_singular: Social Icon
            hint: >
              The name of each social icon should match the name of an SVG file in `/assets/icons`. For example, if you name your icon "github", you need to have an `assets/icons/github.svg` file.
            widget: list
            fields:
              - name: name
                label: Name
                widget: string
              - name: link
                label: Link
                widget: string
      - name: intro
        label: Introduction
        file: src/_includes/intro.md
        description: A brief paragraph or two about you
        fields:
          - name: body
            label: Body
            buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
            editor_components: []
            widget: markdown
  - name: entries
    label: Entries
    label_singular: Entry
    description: Anything that you want to put on your portfolio
    folder: src/entries
    create: true
    editor:
      preview: false
    fields:
      - label: Section
        name: tags
        widget: relation
        collection: general
        file: general
        value_field: sections.*
        display_fields: [sections.*]
        search_fields: [sections.*]
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - {
          label: Start Date,
          name: startDate,
          widget: datetime,
          format: YYYY-MM,
          date_format: MMM YYYY,
          required: false,
        }
      - {
          label: End Date,
          name: endDate,
          widget: datetime,
          format: YYYY-MM,
          date_format: MMM YYYY,
          required: false,
          hint: Leave blank if you're still working on this project,
        }
      - { label: Link, name: link, widget: string, required: false }
      - { label: Skills, name: skills, widget: list }
      - { label: Image, name: image, widget: image, required: false }
      - {
          label: Image Alt Text,
          name: imageAltText,
          widget: string,
          required: false,
        }
